### ISSUE TITLE
Obey standard variables for indentation style

### ISSUE THREAD

**Issue by mcandre** [wwwjfy/emacs-fish#17]
Emacs offers standard variables for configuring indentation styles, such as `indent-tabs-mode` and `sws-tab-width`. When an Emacs user configures these globally, it is expected that the different programming modes respect these settings. Unless overridden, please have fish-mode inform its indentation settings to match `indent-tabs-mode` and `sws-tab-width` by default.

**Comment by wwwjfy** [comment]
I looked at some other builtin programming mode, and failed to find the usage of `indent-tabs-mode` and `sws-tab-width`.

I tried to set `indent-tabs-mode` on, and it works with fish-mode, that a _changed_ indent was tabs, instead of spaces. It won't apply to other lines, which it's not expected to. So I think if you re-indent the files, you can get tabs.

As for `sws-tab-width`, I found it's in an external package called jade-mode, not a built-in variable.
